apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidentlens-correlator
  namespace: observability
  labels:
    app: incidentlens-correlator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidentlens-correlator
  template:
    metadata:
      labels:
        app: incidentlens-correlator
    spec:
      serviceAccountName: incidentlens-correlator
      containers:
        - name: correlator
          image: incidentlens/correlator:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.observability.svc.cluster.local:9090"
            - name: LOKI_URL
              value: "http://loki-gateway.observability.svc.cluster.local"
            - name: TEMPO_URL
              value: "http://tempo.observability.svc.cluster.local:3200"
            - name: DB_PATH
              value: "/data/incidents.db"
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: incidentlens-correlator
  namespace: observability
spec:
  selector:
    app: incidentlens-correlator
  ports:
    - port: 8080
      targetPort: 8080